#!/bin/sh -e

# generate tests

cd $(dirname $0)

sed=sed
if [ `uname` = Darwin ]; then
    sed=gsed
fi

for f in *.cc; do
    g=${f%.c}
    $sed -r -n 's/^void (test[a-z0-9_]+)[(][)] .*/        ts.add_test("\/'"$g\/"'\1", \1);/ p' $f >> init.tmp
    $sed -r -n 's/^void (test[a-z0-9_]+[(][)]) .*/extern void \1;/ p' $f >> extern.tmp
done


cat << EOF
// THIS FILE IS GENERATED by $0

#include <stdlib.h>

#include "tests.h"
EOF

cat extern.tmp

cat << EOF
int main(int argc, const char *argv[]) {
    try {
        test_suite ts;
EOF
cat init.tmp
cat << EOF
        return ts.run(argc, argv);
    } catch (...) {
        std::cerr << current_exception_information();
        return 1;
    }
}
EOF

rm -f init.tmp extern.tmp

# vim: set ts=4 sw=4 et:
